# Site settings
title: Overlord's Blog
header-img: img/wall2.jpg
email: yuyueugene84@gmail.com
description: "70% American, 30% Taiwanese, Eat, Code, Play, Fuck"
baseurl: ""
url: "http://yuyueugene84.github.io"
twitter_username: SBootstrap
github_username:  yuyueugene84
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
